baseURL = "https://kuba86.com/"
title = "kuba86 Â· Scala Spark Engineer Â· Blog"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pagination.pagerSize = 5000

[deployment]
  [[deployment.targets]]
    name = "production"
    URL = "s3://kuba86.com?endpoint=https://s3.garage.kuba86.com&s3ForcePathStyle=true&region=us-east-1"

[params]
  author = "kuba86"
  info = "ðŸŒˆ Scala Spark Engineer ðŸŽ‰ Functional Programming ðŸŽ‰"
  images = ["/img/kuba86.png"]
  description = "kuba86's blog, tutorials and how to's about Scala, Spark and the journey as a Data Engineer"
  keywords = "scala,spark,blog,engineer,data,kuba86,developer,software"
  avatarurl = "img/profile.jpg"
  favicon_16 = "img/kuba86-com-logo-dark-16.png"
  favicon_32 = "img/kuba86-com-logo-dark-32.png"
  touchicon = "img/kuba86-com-logo-dark-256.png"
  since = 2021
  enableTwemoji = false
  colorScheme = "dark"
customCSS = ["css/custom.css"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/kuba86/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/blaszczykjakub/"
[[params.social]]
  name = "RSS"
  icon = "fa fa-rss fa-2x"
  weight = 1
  url = "https://kuba86.github.io/index.xml"

[params.counterdev]
    id = "0a623b7e-4cc9-4d66-bc1a-86b2a4b46be7"

[params.cloudflare]
  token = "ab821c2c2ce94446ac9a6f1e4052f9d4"

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Tags"
  weight = 2
  url = "tags/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about-me/"

[params.giscus]
  repo="kuba86/kuba86.github.io"
  repoID="R_kgDOJ2B7PQ"
  category="Q&A"
  categoryID="DIC_kwDOJ2B7Pc4CXlML"
  mapping="url"
  strict="1"
  reactionsEnabled="1"
  emitMetadata="0"
  inputPosition="top"
  theme="noborder_dark"
  lang="en"
  loading="lazy"
  crossorigin="anonymous"
